apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-deployment-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - sample-app
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
